-- This module is the root of the LTheoryAssemblyConjectureCanonicalLaneLean Lean proof package.
import LTheoryAssemblyConjectureCanonicalLaneLean.Basic
import LTheoryAssemblyConjectureCanonicalLaneLean.SourcePackage
import LTheoryAssemblyConjectureCanonicalLaneLean.SourceDependencies
import LTheoryAssemblyConjectureCanonicalLaneLean.Formalization
import LTheoryAssemblyConjectureCanonicalLaneLean.ReviewerBridge
import LTheoryAssemblyConjectureCanonicalLaneLean.TheoremStatement
import LTheoryAssemblyConjectureCanonicalLaneLean.MathlibObjects
import LTheoryAssemblyConjectureCanonicalLaneLean.AdmissibleClass
import LTheoryAssemblyConjectureCanonicalLaneLean.Projection
import LTheoryAssemblyConjectureCanonicalLaneLean.BridgeLemmas
import LTheoryAssemblyConjectureCanonicalLaneLean.GateLemmas
import LTheoryAssemblyConjectureCanonicalLaneLean.FinalTheorem
import LTheoryAssemblyConjectureCanonicalLaneLean.MathlibStatement
